### ISSUE TITLE
Sorry for the disturbance

### ISSUE THREAD

**Issue by sonderlau** [Yizhou-Jack/Leetcode-Python#1]
I'm interested in your Lipstick Finder project. After I reviewed the code and report you shared on Github, I didn't find anything about the Python Scraper's source code mentioned in the report.
I created an issue in that repo and also emailed you, but no response.
So I'd like to ask if you can make that part of the code public.
Again, I apologize for the intrusion.

**Comment by Yizhou-Jack** [comment]
Hi. Thanks for your interest. You can check our project report for your reference. Also, the backend code is released here: https://github.com/rainwomennowatermelon/LipstickFinder-Backend
I'm not quite sure about the meaning of "Python Scraper" here.
If you are interested in lips region segmentation: Reference to report 3.1.1, we use the face-parsing model to get the lips region. And a pre-trained model is provided in the backend repo. You can find the model code in /models directory.
If you are interested in lips color detection: Reference to report 3.1.2, the code is in app.py Line 86.

**Comment by sonderlau** [comment]
Thanks for your reply.
On page 21 of the report, it says:
> Therefore, we decided to build our own lipstick dataset with python scraping the latest lipsticks data from official cosmetic websites.

Which generated data that was stored in `evaluation/json/lipsticksMod.json`

I'm interested in how to get lipstick data. According to the report, I guess it's a scraper written in Python? 
If so, I would like to request if you can share the scraper's code.

**Comment by Yizhou-Jack** [comment]
Got it. You can get help from @janejl under the project repo.

**Comment by sonderlau** [comment]
Hi. It seems like janejl is busy with her work. But she promised me that she will update codes later that day which was exactly 4 days ago.
I didn't want to bother you anymore, but will you do me a favor and let her know about this?
